package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping(path="/customer") // This means URL's start with /demo (after Application path)
public class MainController {

	@Autowired // This means to get the bean called customerRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private CustomerRepository customerRepository;

	@RequestMapping(value = "/all", method = RequestMethod.GET)
	public List<Customer> getAll() {
		return customerRepository.findAll();
	}


	@RequestMapping(value = "/create", method = RequestMethod.POST)
	public List<Customer> create(@RequestBody Customer user) {
		customerRepository.save(user);

		return customerRepository.findAll();
	}

	@RequestMapping(value = "/delete/{id}", method = RequestMethod.DELETE)
	public List<Customer> remove(@PathVariable long id) {
		customerRepository.delete(id);

		return customerRepository.findAll();
	}

	@PutMapping("/update/{id}")
	public List<Customer> updateBook(@RequestBody Customer user, @PathVariable Long id) {
		Customer currentuser = customerRepository.findOne(id);

		currentuser.setName(user.getName());
		currentuser.setAddress(user.getAddress());
		currentuser.setCountryCode(user.getCountryCode());

		return customerRepository.findAll();
	}
}